Repository Custom-Weather/Custom-Weather-BE, pull requests merged in 2020-06, with the labels that each got.

#27 Mh heroku
  Procfile
Labels: setup

#30 Mh refactor
  book_webscrape.py
  events_api.py
  movie_webscraper.py
  wsgi.py
Labels: API consumption, webscraping

#31 Mhwm testing
  .travis.yml
  requirements.txt
  test_suite.py
Labels: setup

#37 Wm env variables
  events_api.py
  templates/weather.html
  wsgi.py
Labels: refactor
